!tagdefs

# TODO: Meta-descriptions/documentation is a must, find a way to provide these in-line (jsdoc?).

extends: !typescript | # typescript
  return throw new Error('TODO: Implement');

# TODO: This is alias for !typescript return {...}
get: !typescript | # typescript
  return throw new Error('TODO: Implement');

# TODO: This is an alias to !typescript, similar to !get
set: !typescript | # typescript
  return throw new Error('TODO: Implement');
